# Generated by Django 5.0.2 on 2025-03-27 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='title',
        ),
        migrations.RemoveField(
            model_name='master',
            name='category',
        ),
        migrations.RemoveField(
            model_name='master',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='master',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='master',
            name='description',
        ),
        migrations.RemoveField(
            model_name='master',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='master',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='master',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_certificates', to='main.master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='master',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='master',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='master',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization',
            field=models.CharField(blank=True, choices=[('hair', 'Парикмахер'), ('nails', 'Мастер маникюра'), ('makeup', 'Визажист'), ('massage', 'Массажист'), ('cosmetology', 'Косметолог')], max_length=50),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='main.master')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
