# Generated by Django 5.0.2 on 2025-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_referralcode_referralinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='masters', to='main.service'),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.CharField(blank=True, choices=[('hair', 'Парикмахер'), ('nails', 'Мастер маникюра'), ('makeup', 'Визажист'), ('massage', 'Массажист'), ('cosmetology', 'Косметолог'), ('lashes', 'Лэшмейкер'), ('brows', 'Бровист'), ('permanent', 'Мастер перманентного макияжа'), ('epilation', 'Мастер эпиляции')], max_length=50),
        ),
    ]
