# Generated by Django 5.0.2 on 2025-03-27 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_master_services_alter_master_specialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=6, verbose_name='PIN-код')),
                ('is_biometric_enabled', models.BooleanField(default=False, verbose_name='Биометрия включена')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Последний вход')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIN-код пользователя',
                'verbose_name_plural': 'PIN-коды пользователей',
            },
        ),
    ]
